#!/usr/bin/env python3
from pathlib import Path

p = Path('src/core/k3_ops.c')
s = p.read_text()

old = '''    if (!k3_pair_ready)  k3_pair_init();\n    if (!k3_e8m0_ready)  k3_e8m0_init();\n\n#ifdef _OPENMP\n'''
new = '''    if (!k3_pair_ready)  k3_pair_init();\n    if (!k3_e8m0_ready)  k3_e8m0_init();\n\n#if defined(__AVX2__)\n    /* Fast exact-K3 path. E2M1 values are all integer multiples of 0.5, so represent\n     * each nibble as a signed half-unit in one pshufb, then widen directly to double.\n     * This removes the store+reload through wf[64] while preserving the old two-vector\n     * FMA partition and reduction order bit for bit. The generic path below remains the\n     * fallback for non-32 groups and tails. */\n    const __m128i mx_mask = _mm_set1_epi8(0x0f);\n    const __m128i mx_half_units = _mm_setr_epi8(\n         0,  1,  2,  3,  4,  6,  8, 12,\n         0, -1, -2, -3, -4, -6, -8,-12);\n    const __m256d mx_half = _mm256_set1_pd(0.5);\n#endif\n\n#ifdef _OPENMP\n'''
if s.count(old) != 1:
    raise SystemExit(f'init anchor count={s.count(old)}')
s = s.replace(old, new, 1)

old = '''            int n = in - g * group;\n            if (n > group) n = group;\n\n            /* Expand the group to floats first, then take a plain dot product. The\n'''
new = '''            int n = in - g * group;\n            if (n > group) n = group;\n\n#if defined(__AVX2__)\n            if (group == 32 && n == 32) {\n                /* 16 packed bytes -> 32 signed half-units. Low nibble is the even\n                 * element, matching K3_E2M1_PAIR and the checkpoint pack order. */\n                const __m128i b = _mm_loadu_si128((const __m128i *)pb);\n                const __m128i lo = _mm_shuffle_epi8(\n                    mx_half_units, _mm_and_si128(b, mx_mask));\n                const __m128i hi = _mm_shuffle_epi8(\n                    mx_half_units, _mm_and_si128(_mm_srli_epi16(b, 4), mx_mask));\n                const __m128i q0 = _mm_unpacklo_epi8(lo, hi);\n                const __m128i q1 = _mm_unpackhi_epi8(lo, hi);\n                __m256d v0 = _mm256_setzero_pd(), v1 = _mm256_setzero_pd();\n\n                /* Same lane ownership as the old wf[] AVX2 loop:\n                 * v0 gets 0..3,8..11,16..19,24..27; v1 gets the interleaving fours.\n                 * int->double and *0.5 are exact for every E2M1 code, and x float->double\n                 * is exact too, so each FMA sees the same operands in the same order. */\n#define K3_MX_DO4(V, Q, SHIFT, XOFF) do {                                      \\\n                    const __m128i qq = _mm_cvtepi8_epi32(                       \\\n                        _mm_srli_si128((Q), (SHIFT)));                           \\\n                    const __m256d qw = _mm256_mul_pd(                           \\\n                        _mm256_cvtepi32_pd(qq), mx_half);                        \\\n                    (V) = _mm256_fmadd_pd(qw,                                   \\\n                        _mm256_cvtps_pd(_mm_loadu_ps(xg + (XOFF))), (V));        \\\n                } while (0)\n                K3_MX_DO4(v0, q0,  0,  0); K3_MX_DO4(v1, q0,  4,  4);\n                K3_MX_DO4(v0, q0,  8,  8); K3_MX_DO4(v1, q0, 12, 12);\n                K3_MX_DO4(v0, q1,  0, 16); K3_MX_DO4(v1, q1,  4, 20);\n                K3_MX_DO4(v0, q1,  8, 24); K3_MX_DO4(v1, q1, 12, 28);\n#undef K3_MX_DO4\n                double a[4];\n                _mm256_storeu_pd(a, _mm256_add_pd(v0, v1));\n                const double sub = (a[0] + a[1]) + (a[2] + a[3]);\n                acc += sub * (double)K3_E8M0[sb];\n                continue;\n            }\n#endif\n\n            /* Generic/scalar fallback: expand the group to floats first, then take a\n             * plain dot product. Kept unchanged for non-K3 geometry and partial tails.\n'''
if s.count(old) != 1:
    raise SystemExit(f'group anchor count={s.count(old)}')
s = s.replace(old, new, 1)
p.write_text(s)
print('patched src/core/k3_ops.c')
